// RevOS Demo Data — Embedded telecom accounts for demo mode

export const DEMO_ACCOUNTS = [
  {
    id: 'cust1',
    name: 'Customer 1',
    vertical: 'Carrier',
    arr: 515299,
    mrr: 42941,
    pipeline_mrr: 34639,
    pipeline_count: 14,
    won: 22,
    lost: 4,
    win_rate: 0.846,
    avg_cycle: 23,
    nrr: 1.12,
    days_silent: 14,
    velocity: 'accelerating',
    risk_score: 18,
    risk_level: 'moderate',
    rep: 'William Good',
    sales_owner: 'William Good',
    reps: 11,
    tenure_mo: 62,
    disconnects: 2,
    downgrades: 2,
    downgrade_mrr: 2050,
    lost_mrr: 10750,
    products: ['Wavelengths - Long Haul', 'Dark Fiber - Metro'],
    concentration: {
      'Wavelengths - Long Haul': { mrr: 29140, pct: 0.68 },
      'Dark Fiber - Metro': { mrr: 13802, pct: 0.32 },
    },
    pipeline_by_stage: {
      Discover: { count: 7, mrr: 20860 },
      Design: { count: 2, mrr: 0 },
      Propose: { count: 3, mrr: 7061 },
      Negotiate: { count: 2, mrr: 6718 },
    },
    predictions: [
      { product: 'Dark Fiber - Metro', event: 'expansion', prior: 0.35, posterior: 0.78, mrr: '$3,000-$5,000', timing: '30-60 days', evidence: ['2 deals in Negotiate stage', 'Accelerating velocity (13 deals in 6mo)', 'Historical 90-day purchase cadence — currently at day 40'], direction: 'strengthened', confidence: 0.82 },
      { product: 'IP Services', event: 'new_purchase', prior: 0.15, posterior: 0.42, mrr: '$4,000-$8,000', timing: '60-90 days', evidence: ['Cross-sell gap: Carrier vertical buys IP 87% of the time', '14 active deals signal infrastructure buildout', 'No IP in current portfolio despite heavy fiber/wavelength footprint'], direction: 'strengthened', confidence: 0.71 },
      { product: 'Wavelengths - Long Haul', event: 'expansion', prior: 0.40, posterior: 0.65, mrr: '$4,000-$10,000', timing: '30-45 days', evidence: ['4 Discover-stage wavelength deals', '68% of revenue = wavelengths, natural expansion vector', 'Recent $10K+/mo wavelength wins signal ongoing capacity buildout'], direction: 'strengthened', confidence: 0.77 },
    ],
    cross_sell: [
      { product: 'IP Services', prob: 0.42, reason: 'Carrier customers buying wavelengths and dark fiber purchase IP 87% of the time. Gap likely means competitor-served.', trigger: 'Mention IP bundling during next Negotiate-stage conversation' },
      { product: 'Ethernet', prob: 0.28, reason: 'Natural complement to dark fiber for last-mile delivery. 4 of 5 similar carrier accounts have Ethernet.', trigger: 'Technical review meeting — ask about last-mile connectivity needs' },
    ],
    churn_preds: [
      { product: 'Wavelengths - Long Haul', prob: 0.15, timing: '6-12 months', signals: ['3 recent Close-Lost wavelength deals ($10,750)', 'Commoditization pressure on wavelength pricing', '2 disconnects in 2025'], action: 'Lock in multi-year agreement with volume discount to prevent circuit-by-circuit attrition' },
    ],
    portfolio_health: 'growing',
    arr_12mo_change: '+$60K-$100K',
    active_deals: [
      { product: 'Dark Fiber - Metro', mrr: 3255, stage: 'Negotiate', forecast: 'Best Case', close: '4/30/2026', rep: 'William Good', sales_channel: 'Premier' },
      { product: 'Dark Fiber - Metro', mrr: 3463, stage: 'Negotiate', forecast: 'Best Case', close: '4/30/2026', rep: 'William Good', sales_channel: 'Premier' },
      { product: 'Dark Fiber - Metro', mrr: 4561, stage: 'Propose', forecast: 'Longshot', close: '4/30/2026', rep: 'William Good', sales_channel: 'Premier' },
      { product: 'Wavelengths - Long Haul', mrr: 3961, stage: 'Discover', forecast: 'Not In Forecast', close: '3/31/2026', rep: 'William Good', sales_channel: 'Premier' },
      { product: 'Wavelengths - Long Haul', mrr: 4065, stage: 'Discover', forecast: 'Not In Forecast', close: '3/31/2026', rep: 'William Good', sales_channel: 'Premier' },
    ],
    funnel_closed: [
      { product: 'Wavelengths - Long Haul', mrr: 4494, stage: 'closed won', type: 'New Service', close: '1/15/2026', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Dark Fiber - Metro', mrr: 3200, stage: 'closed won', type: 'New Service', close: '2/10/2026', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Wavelengths - Long Haul', mrr: 1293, stage: 'closed won', type: 'Positive Re-Rate', close: '3/5/2026', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Wavelengths - Long Haul', mrr: 20121, stage: 'closed won', type: 'New Service', close: '8/15/2025', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Dark Fiber - Metro', mrr: 12579, stage: 'closed won', type: 'New Service', close: '10/1/2025', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Wavelengths - Long Haul', mrr: 8987, stage: 'closed won', type: 'New Service', close: '11/20/2025', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Wavelengths - Long Haul', mrr: -1200, stage: 'closed won', type: 'Negative Re-Rate', close: '8/1/2025', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Dark Fiber - Metro', mrr: -850, stage: 'closed won', type: 'Negative Re-Rate', close: '1/15/2026', rep: 'William Good', sales_channel: 'Premier', forecast: 'Closed' },
    ],
    historical_deals: [],
    game_theory: {
      win_prob: 0.82,
      value: '$3,255/mo ($39K ARR)',
      buyer_urgency: 'high',
      competition: 'moderate',
      info_edge: 'seller',
      strategy: { name: 'Accelerate Close — Bundle Lock', type: 'bundle_lock', rationale: 'Two Negotiate-stage fiber deals from same account. Bundle into single MSA with volume pricing. The buyer is expanding infrastructure rapidly (14 deals) — they want speed and simplicity, not lowest price. Your physical fiber presence is non-replicable.' },
      nash: 'Seller bundles both Negotiate deals into MSA; buyer accepts because switching costs for lit dark fiber are prohibitive and timeline is urgent. Competitor\'s best response is to target wavelength pricing on future deals rather than contest active fiber.',
      sequence: [
        { move: 1, actor: 'seller', action: 'Present combined proposal for both Negotiate-stage fiber deals as single MSA', response: 'Buyer evaluates total package vs. individual circuits', timing: 'This week' },
        { move: 2, actor: 'buyer', action: 'Requests 5-8% discount for commitment', response: 'Offer 3% + waived install fees (higher perceived value, lower cost)', timing: 'Week 2' },
        { move: 3, actor: 'seller', action: 'Introduce IP Services discussion while momentum is high', response: 'Buyer agrees to technical review meeting', timing: 'Week 3' },
      ],
      pricing: {
        anchor: '$3,255/mo per circuit (list rate)',
        floor: '$2,930/mo (10% max discount)',
        value_levers: ['Waived installation ($15K value per circuit)', 'Dedicated project manager for both circuits', 'Priority provisioning (30-day vs. 60-day standard)', 'Future wavelength pricing lock for 12 months'],
        bundles: ['Both fiber circuits + 12-month wavelength commitment = 5% blended', 'Add IP Services DIA = additional 3% across all products'],
      },
      concessions: [
        { if_says: 'Your competitor quoted 15% less on similar fiber routes.', respond: 'On a single-circuit basis, that may be true for certain routes. But when we look at your total infrastructure — 14 active projects — an MSA structure gives you a blended rate that individual circuit quotes can\'t match. Plus, our fiber is already in-building at 8 of your 10 target locations.', cost: '0% — reframing, no actual discount', value: 'High — shifts comparison from price to total value' },
        { if_says: 'We need to push the timeline out 60 days.', respond: 'I understand timeline flexibility. However, I should let you know that our install crews are currently scheduled for your routes in the next 30 days. If we push past that window, the next available slot is 90+ days out. I\'d recommend we lock the agreement now with a flexible start date.', cost: 'Low — schedule hold costs minimal', value: 'High — creates urgency without being aggressive' },
      ],
      competitive: {
        competitor_offer: 'Regional fiber provider quoting 12-15% below on individual dark fiber circuits',
        differentiation: 'In-building presence at 8 of 10 target locations. Competitor would require new construction (6-12 month lead time vs. 30 days). Total cost of delay exceeds any per-circuit savings.',
        trap: 'Ask buyer to compare total project timeline and construction risk, not just monthly rate.',
      },
      closing: ['Buyer asks about implementation timeline specifics', 'Buyer introduces procurement/legal team to the conversation', 'Buyer requests contract redline rather than asking for more proposals', 'References to \'when we go live\' rather than \'if we choose you\''],
      walk_away: ['Buyer demands >15% discount with no volume commitment', 'Buyer reveals they\'ve already signed with competitor for primary routes', 'Decision timeline extends beyond 120 days with no executive engagement'],
      talk_track: 'I\'ve put together a combined proposal for both fiber circuits that gives you better economics than individual quotes. Given that we already have fiber in-building at most of your target locations, we can have both circuits lit within 30 days of signing. I\'d also like to schedule a technical review to discuss how our IP Services portfolio could simplify your network architecture as you scale.',
    },
    signals: {
      company_summary: 'Customer 1 is a major regional carrier expanding fiber and wavelength infrastructure across the western US. Recent FCC filings indicate spectrum acquisition for 5G backhaul, and the company has announced $200M in capital expenditure for 2026 network buildout.',
      signal_strength: 'strong',
      match_confidence: 0.92,
      items: [
        { headline: '$200M CapEx plan announced for 2026 network expansion', type: 'expansion', urgency: 'act_now', impact: 'Major infrastructure buildout = sustained demand for dark fiber and wavelengths over 12-18 months. Pipeline should grow significantly beyond current 14 deals.', confidence: 0.88 },
        { headline: 'FCC spectrum acquisition filing for 5G backhaul', type: 'regulatory', urgency: 'this_week', impact: '5G backhaul requires fiber connectivity to tower sites. New product opportunity for small-cell fiber connections. Opens door to IP transit discussion.', confidence: 0.85 },
        { headline: 'New VP of Network Engineering hired from competitor', type: 'leadership', urgency: 'this_month', impact: 'New technical leader may re-evaluate vendor relationships. Risk: could favor previous employer\'s solutions. Opportunity: fresh relationship, chance to demonstrate technical depth.', confidence: 0.79 },
        { headline: 'Q4 2025 earnings: 18% YoY revenue growth, upgraded guidance', type: 'financial', urgency: 'monitor', impact: 'Strong financial health confirms ability to fund infrastructure expansion. Low churn risk on existing services. Budget availability for new purchases.', confidence: 0.91 },
      ],
    },
    backtest: [
      { q: '2024 Q3', actual: { outcome: 'expanded', won_mrr: 20121, lost_mrr: 0, net: 20121 }, predicted: { outcome: 'expanded', churn: 'low', confidence: 0.78 }, score: 90 },
      { q: '2024 Q4', actual: { outcome: 'grew_modestly', won_mrr: 44, lost_mrr: 0, net: 44 }, predicted: { outcome: 'stable', churn: 'low', confidence: 0.65 }, score: 60 },
      { q: '2025 Q1', actual: { outcome: 'churned/contracted', won_mrr: 20, lost_mrr: 5200, net: -5180 }, predicted: { outcome: 'stable', churn: 'low', confidence: 0.62 }, score: 20 },
      { q: '2025 Q2', actual: { outcome: 'expanded', won_mrr: 10000, lost_mrr: 3800, net: 6200 }, predicted: { outcome: 'expanded', churn: 'medium', confidence: 0.71 }, score: 70 },
      { q: '2025 Q3', actual: { outcome: 'churned/contracted', won_mrr: 12579, lost_mrr: 1750, net: 10829 }, predicted: { outcome: 'expanded', churn: 'medium', confidence: 0.68 }, score: 50 },
      { q: '2025 Q4', actual: { outcome: 'expanded', won_mrr: 8987, lost_mrr: 0, net: 8987 }, predicted: { outcome: 'expanded', churn: 'low', confidence: 0.74 }, score: 80 },
      { q: '2026 Q1', actual: { outcome: 'expanded', won_mrr: 4494, lost_mrr: 0, net: 4494 }, predicted: { outcome: 'expanded', churn: 'low', confidence: 0.81 }, score: 90 },
    ],
    losses: {
      deals: [
        { product: 'Wavelengths - Long Haul', mrr: 5200, date: '6/15/2025', type: 'New Service', rep: 'William Good', days_pipe: 97 },
        { product: 'Dark Fiber - Metro', mrr: 3800, date: '9/22/2025', type: 'New Service', rep: 'William Good', days_pipe: 113 },
        { product: 'Wavelengths - Long Haul', mrr: 1750, date: '11/30/2025', type: 'New Service', rep: 'Michael Kahn', days_pipe: 107 },
        { product: 'Wavelengths - Long Haul', mrr: 0, date: '1/2/2022', type: 'Positive Re-Rate', rep: 'Usama Fayyaz', days_pipe: 90 },
      ],
      disconnects: [{ product: 'Wavelengths - Long Haul', date: '4/15/2025' }, { product: 'Dark Fiber - Metro', date: '7/20/2025' }],
      downgrades: [{ product: 'Wavelengths - Long Haul', mrr: -1200, date: '8/1/2025' }, { product: 'Dark Fiber - Metro', mrr: -850, date: '1/15/2026' }],
      by_product: { 'Wavelengths - Long Haul': { count: 3, mrr: 6950 }, 'Dark Fiber - Metro': { count: 1, mrr: 3800 } },
      timeline: [
        { q: '2022 Q1', lost: 0, disc: 0, down: 0 },
        { q: '2025 Q2', lost: 5200, disc: 1, down: 0 },
        { q: '2025 Q3', lost: 3800, disc: 1, down: 1200 },
        { q: '2025 Q4', lost: 1750, disc: 0, down: 0 },
        { q: '2026 Q1', lost: 0, disc: 0, down: 850 },
      ],
    },
    revenue_tl: [
      { q: '2021 Q1', new: 949, rr_up: 8, rr_down: 0, lost: 0, net: 957, cum: 957 },
      { q: '2021 Q4', new: 0, rr_up: 50, rr_down: 0, lost: 0, net: 50, cum: 1007 },
      { q: '2022 Q4', new: 0, rr_up: 91, rr_down: 0, lost: 0, net: 91, cum: 1098 },
      { q: '2023 Q4', new: 0, rr_up: 43, rr_down: 0, lost: 0, net: 43, cum: 1141 },
      { q: '2024 Q1', new: 0, rr_up: 20, rr_down: 0, lost: 0, net: 20, cum: 1161 },
      { q: '2024 Q4', new: 0, rr_up: 44, rr_down: 0, lost: 0, net: 44, cum: 1205 },
      { q: '2025 Q2', new: 0, rr_up: 0, rr_down: 0, lost: 5200, net: -5200, cum: -3995 },
      { q: '2025 Q3', new: 20121, rr_up: 0, rr_down: -1200, lost: 3800, net: 15121, cum: 11126 },
      { q: '2025 Q4', new: 12579, rr_up: 46, rr_down: 0, lost: 1750, net: 10875, cum: 22001 },
      { q: '2026 Q1', new: 8987, rr_up: 5, rr_down: -850, lost: 0, net: 8142, cum: 30143 },
    ],
    learning: [
      { deals: 5, accuracy: 32, churn: 20, expand: 40, outcome: 25 },
      { deals: 10, accuracy: 45, churn: 35, expand: 50, outcome: 40 },
      { deals: 15, accuracy: 58, churn: 50, expand: 60, outcome: 55 },
      { deals: 20, accuracy: 67, churn: 65, expand: 70, outcome: 62 },
      { deals: 25, accuracy: 74, churn: 72, expand: 75, outcome: 70 },
      { deals: 30, accuracy: 79, churn: 78, expand: 80, outcome: 76 },
      { deals: 35, accuracy: 83, churn: 82, expand: 84, outcome: 81 },
      { deals: 40, accuracy: 85, churn: 84, expand: 86, outcome: 84 },
    ],
    locations: [
      { name: 'Denver POP - 900 Auraria', type: 'Data Center', lat: 39.7456, lng: -105.0069, status: 'on-net', lit: true, services: 2, mrr: 20121, products: ['Wavelengths - Long Haul'], note: 'Primary POP. 2x100G wavelengths to COS.' },
      { name: 'Centennial Medical Campus', type: 'Hospital', lat: 39.7329, lng: -104.9408, status: 'on-net', lit: true, services: 4, mrr: 12579, products: ['Dark Fiber - Metro'], note: 'Main campus. 4 buildings connected via intra-campus fiber.' },
      { name: 'Springs Campus', type: 'Hospital', lat: 38.8561, lng: -104.8214, status: 'on-net', lit: true, services: 2, mrr: 10121, products: ['Wavelengths - Long Haul'], note: 'Secondary campus. Wavelength to Denver.' },
      { name: 'Pueblo Clinic', type: 'Branch', lat: 38.2650, lng: -104.6127, status: 'near-net', lit: false, services: 0, mrr: 0, products: [], note: 'New clinic Q3 2026. Fiber within 800ft.' },
      { name: 'Fort Collins Medical', type: 'Branch', lat: 40.5853, lng: -105.0844, status: 'near-net', lit: false, services: 0, mrr: 0, products: [], note: 'Satellite office. Near-net fiber available.' },
      { name: 'Grand Junction Clinic', type: 'Branch', lat: 39.0639, lng: -108.5506, status: 'off-net', lit: false, services: 0, mrr: 0, products: [], note: 'Western slope. No fiber. New build required.' },
      { name: 'Boulder Research Lab', type: 'Office', lat: 40.0150, lng: -105.2705, status: 'near-net', lit: false, services: 0, mrr: 0, products: [], note: 'Research facility. Dark fiber prospect.' },
      { name: 'DIA Medical Facility', type: 'Branch', lat: 39.8561, lng: -104.6737, status: 'on-net', lit: true, services: 1, mrr: 4494, products: ['Wavelengths - Long Haul'], note: 'Airport facility. Recently lit wavelength.' },
    ],
  },
  {
    id: 'cust2',
    name: 'Customer 2',
    vertical: 'Software & Tech',
    arr: 448786,
    mrr: 37399,
    pipeline_mrr: 1000,
    pipeline_count: 1,
    won: 34,
    lost: 5,
    win_rate: 0.872,
    avg_cycle: 30,
    nrr: 0.87,
    days_silent: 497,
    velocity: 'stalled',
    risk_score: 62,
    risk_level: 'critical',
    rep: 'Jose Banales',
    sales_owner: 'Jose Banales',
    reps: 19,
    tenure_mo: 75,
    disconnects: 3,
    downgrades: 3,
    downgrade_mrr: 4850,
    lost_mrr: 12200,
    products: ['IP Services', 'zColo', 'Ethernet', 'Dark Fiber - Metro'],
    concentration: {
      zColo: { mrr: 13848, pct: 0.37 },
      'IP Services': { mrr: 17201, pct: 0.46 },
      Ethernet: { mrr: 6133, pct: 0.16 },
      'Dark Fiber - Metro': { mrr: 217, pct: 0.01 },
    },
    pipeline_by_stage: { 'Design Solution': { count: 1, mrr: 1000 } },
    predictions: [
      { product: 'IP Services', event: 'churn', prior: 0.20, posterior: 0.52, mrr: '-$3,000-$8,000', timing: '60-90 days', evidence: ['2 recent IP losses ($5,300 MRR)', '497 days since last activity', 'NRR below 90% — account is contracting', 'New VP of Engineering may consolidate vendors'], direction: 'strengthened', confidence: 0.74 },
      { product: 'zColo', event: 'churn', prior: 0.15, posterior: 0.38, mrr: '-$5,000-$13,000', timing: '3-6 months', evidence: ['3 colo disconnects in last 18 months', 'Cloud migration trend in Software & Tech vertical', '$2,400 colo downgrade in Q1 2024'], direction: 'strengthened', confidence: 0.68 },
      { product: 'IP Services', event: 'renewal', prior: 0.60, posterior: 0.45, mrr: '$2,000-$5,000', timing: '90+ days', evidence: ['Only active pipeline deal is Longshot', '19 reps = no relationship continuity', '497 days silence = lowest engagement in account history'], direction: 'weakened', confidence: 0.61 },
    ],
    cross_sell: [{ product: 'Cloud Connect', prob: 0.35, reason: 'Software companies migrating from colo to cloud need connectivity bridges. This is the natural next step.', trigger: 'Strategic Business Review — ask about AWS/Azure adoption plans' }],
    churn_preds: [
      { product: 'zColo', prob: 0.38, timing: '3-6 months', signals: ['3 disconnects', 'Cloud migration pressure', '$2,400 downgrade'], action: 'Schedule colo contract review. Offer hybrid cloud connectivity package before next renewal.' },
      { product: 'IP Services', prob: 0.52, timing: '60-90 days', signals: ['2 losses', '497 days silent', 'Negative velocity'], action: 'Immediate re-engagement. Assign dedicated rep. Executive outreach within 1 week.' },
    ],
    portfolio_health: 'at_risk',
    arr_12mo_change: '-$30K-$60K',
    active_deals: [{ product: 'IP Services', mrr: 1000, stage: 'Design Solution', forecast: 'Longshot', close: '10/31/2026', rep: 'Jose Banales', sales_channel: 'Premier' }],
    funnel_closed: [
      { product: 'IP Services', mrr: 2800, stage: 'closed won', type: 'New Service', close: '2/15/2026', rep: 'Jose Banales', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'zColo', mrr: 5500, stage: 'closed won', type: 'New Service', close: '7/20/2025', rep: 'Jose Banales', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'IP Services', mrr: 3200, stage: 'closed won', type: 'Renewal', close: '9/10/2025', rep: 'Jose Banales', sales_channel: 'Premier', forecast: 'Closed' },
      { product: 'Ethernet', mrr: -2100, stage: 'closed won', type: 'Negative Re-Rate', close: '11/5/2025', rep: 'Jose Banales', sales_channel: 'Premier', forecast: 'Closed' },
    ],
    historical_deals: [],
    game_theory: {
      win_prob: 0.35,
      value: '$1,000/mo ($12K ARR)',
      buyer_urgency: 'low',
      competition: 'fierce',
      info_edge: 'buyer',
      strategy: { name: 'Relationship Recovery — Value Reframe', type: 'value_reframe', rationale: 'This deal is a lifeline for a $449K ARR account that\'s gone dark. The $1K/mo deal itself is small, but it represents the only active engagement. Use it as the entry point to re-establish the relationship, not as a standalone negotiation.' },
      nash: 'Buyer has all the leverage — they know you\'ve been absent for 16 months and competitors are offering alternatives. Your equilibrium move is to over-invest in this deal (concede on price) to re-establish presence, then leverage the colo stickiness to rebuild the broader relationship.',
      sequence: [
        { move: 1, actor: 'seller', action: 'Executive-level outreach acknowledging the gap, requesting Strategic Business Review', response: 'Buyer cautiously agrees to meeting', timing: 'This week' },
        { move: 2, actor: 'buyer', action: 'Reveals they\'ve been evaluating cloud migration and competitor IP offerings', response: 'Listen, document, don\'t pitch. Acknowledge their evaluation is reasonable.', timing: 'Week 2' },
        { move: 3, actor: 'seller', action: 'Present hybrid cloud connectivity proposal + IP deal with aggressive pricing', response: 'Buyer compares to competitor proposals', timing: 'Week 4' },
      ],
      pricing: {
        anchor: '$1,000/mo (current proposal)',
        floor: '$750/mo (25% discount)',
        value_levers: ['Free 90-day proof of concept', 'Dedicated technical account manager', 'Cloud connectivity assessment at no cost', 'Bundle with colo renewal for blended pricing'],
        bundles: ['IP + Cloud Connect + colo renewal = 15% blended discount', 'Multi-year commitment = additional 5%'],
      },
      concessions: [
        { if_says: 'We\'ve been getting better pricing from CloudNet for the last year.', respond: 'That\'s fair — and I\'ll be direct, we haven\'t been showing up for you the way we should have. Rather than competing on price alone, I\'d like to show you our cloud connectivity roadmap that integrates with your existing colo footprint. That\'s something CloudNet can\'t offer because your infrastructure is physically in our facility.', cost: 'Moderate — may need 10-15% discount to match', value: 'High — shifts conversation from commodity pricing to integrated value' },
      ],
      competitive: {
        competitor_offer: 'CloudNet offering IP transit at 20% below your rates with cloud-native bundling',
        differentiation: 'Physical colo presence — their servers are in your facility. Cloud connectivity that bridges on-prem and cloud. Integrated billing across all services.',
        trap: 'Ask buyer to model the total cost of migrating colo workloads to a new provider vs. leveraging existing infrastructure with cloud connectivity overlay.',
      },
      closing: ['Buyer asks to include colo team in next meeting', 'Buyer shares their cloud migration timeline', 'Buyer asks about multi-year pricing'],
      walk_away: ['Buyer has already signed 3-year deal with competitor for IP', 'Colo contract is not renewing and they\'ve begun physical migration', 'No executive engagement after 3 outreach attempts'],
      talk_track: 'I want to start by acknowledging something — we haven\'t been the partner you deserve over the last 16 months, and that changes today. I\'ve been assigned as your dedicated account manager, and my first priority is understanding where your infrastructure strategy is heading. I know you\'re evaluating options, and I think there\'s a compelling story around how your existing colo footprint connects to wherever you\'re going with cloud.',
    },
    signals: {
      company_summary: 'Customer 2 is a mid-market software company that has been shifting workloads to AWS over the past 18 months. Recent job postings indicate hiring for cloud infrastructure roles, and the company announced a $45M Series C focused on platform scalability.',
      signal_strength: 'strong',
      match_confidence: 0.88,
      items: [
        { headline: '$45M Series C announced — platform scalability focus', type: 'funding', urgency: 'act_now', impact: 'Capital infusion means infrastructure spend is increasing. But direction matters: if it\'s all going to cloud, colo and traditional IP are at risk. If hybrid, opportunity to position cloud connectivity.', confidence: 0.90 },
        { headline: 'Hiring 3 Cloud Infrastructure Engineers (AWS focus)', type: 'technology', urgency: 'this_week', impact: 'Confirms cloud migration trajectory. On-prem/colo workloads likely decreasing. Need to pivot positioning from traditional infrastructure to cloud connectivity and hybrid solutions.', confidence: 0.86 },
        { headline: 'CTO keynote at re:Invent mentioned \'cloud-first infrastructure strategy\'', type: 'leadership', urgency: 'act_now', impact: 'CTO publicly committed to cloud-first. Colo and traditional IP positioning must shift to \'cloud enablement\' — interconnection, Direct Connect, low-latency bridges. Existing framing will not resonate.', confidence: 0.83 },
        { headline: 'Glassdoor reviews mention \'aging infrastructure\' as pain point', type: 'risk', urgency: 'this_month', impact: 'Internal frustration with current infrastructure = both risk (they want change) and opportunity (position as the modernization partner, not the legacy vendor).', confidence: 0.62 },
      ],
    },
    backtest: [
      { q: '2024 Q1', actual: { outcome: 'grew_modestly', won_mrr: 949, lost_mrr: 0, net: 949 }, predicted: { outcome: 'stable', churn: 'low', confidence: 0.60 }, score: 50 },
      { q: '2024 Q2', actual: { outcome: 'churned/contracted', won_mrr: 0, lost_mrr: 1800, net: -1800 }, predicted: { outcome: 'stable', churn: 'medium', confidence: 0.55 }, score: 40 },
      { q: '2024 Q3', actual: { outcome: 'churned/contracted', won_mrr: 0, lost_mrr: 4500, net: -4500 }, predicted: { outcome: 'churned/contracted', churn: 'high', confidence: 0.72 }, score: 90 },
      { q: '2024 Q4', actual: { outcome: 'dormant', won_mrr: 0, lost_mrr: 0, net: 0 }, predicted: { outcome: 'dormant', churn: 'medium', confidence: 0.65 }, score: 80 },
      { q: '2025 Q1', actual: { outcome: 'dormant', won_mrr: 0, lost_mrr: 0, net: 0 }, predicted: { outcome: 'dormant', churn: 'high', confidence: 0.70 }, score: 80 },
    ],
    losses: {
      deals: [
        { product: 'IP Services', mrr: 3500, date: '8/15/2023', type: 'New Service', rep: 'Andrew Jahant', days_pipe: 106 },
        { product: 'Ethernet', mrr: 2200, date: '2/10/2024', type: 'New Service', rep: 'Andrew Jahant', days_pipe: 87 },
        { product: 'IP Services', mrr: 1800, date: '7/30/2024', type: 'New Service', rep: 'Andrew Jahant', days_pipe: 99 },
        { product: 'zColo', mrr: 4500, date: '11/5/2024', type: 'New Service', rep: 'Jennifer Middleton', days_pipe: 96 },
        { product: 'zColo', mrr: 200, date: '2/28/2021', type: 'New Service', rep: 'Joseph Quick', days_pipe: 88 },
      ],
      disconnects: [{ product: 'zColo', date: '6/1/2023' }, { product: 'zColo', date: '1/15/2024' }, { product: 'Ethernet', date: '5/1/2024' }],
      downgrades: [{ product: 'zColo', mrr: -2400, date: '3/1/2024' }, { product: 'IP Services', mrr: -1650, date: '9/15/2024' }, { product: 'zColo', mrr: -800, date: '12/1/2024' }],
      by_product: { 'IP Services': { count: 2, mrr: 5300 }, Ethernet: { count: 1, mrr: 2200 }, zColo: { count: 2, mrr: 4700 } },
      timeline: [
        { q: '2023 Q3', lost: 3500, disc: 1, down: 0 },
        { q: '2024 Q1', lost: 2200, disc: 1, down: 2400 },
        { q: '2024 Q2', lost: 1800, disc: 1, down: 0 },
        { q: '2024 Q3', lost: 0, disc: 0, down: 1650 },
        { q: '2024 Q4', lost: 4500, disc: 0, down: 800 },
      ],
    },
    revenue_tl: [
      { q: '2020 Q1', new: 1840, rr_up: 0, rr_down: 0, lost: 0, net: 1840, cum: 1840 },
      { q: '2020 Q2', new: 14200, rr_up: 22, rr_down: 0, lost: 0, net: 14222, cum: 16062 },
      { q: '2020 Q3', new: 1550, rr_up: 18, rr_down: 0, lost: 0, net: 1568, cum: 17630 },
      { q: '2021 Q2', new: 1870, rr_up: 117, rr_down: 0, lost: 0, net: 1987, cum: 19617 },
      { q: '2022 Q2', new: 2133, rr_up: 9422, rr_down: 0, lost: 0, net: 11555, cum: 31172 },
      { q: '2023 Q1', new: 1312, rr_up: 0, rr_down: 0, lost: 0, net: 1312, cum: 32484 },
      { q: '2023 Q3', new: 0, rr_up: 1406, rr_down: 0, lost: 3500, net: -2094, cum: 30390 },
      { q: '2024 Q1', new: 949, rr_up: 0, rr_down: -2400, lost: 2200, net: -3651, cum: 26739 },
      { q: '2024 Q3', new: 0, rr_up: 0, rr_down: -1650, lost: 6300, net: -7950, cum: 18789 },
    ],
    learning: [
      { deals: 10, accuracy: 28, churn: 20, expand: 35, outcome: 22 },
      { deals: 20, accuracy: 42, churn: 38, expand: 45, outcome: 38 },
      { deals: 30, accuracy: 55, churn: 52, expand: 55, outcome: 50 },
      { deals: 40, accuracy: 65, churn: 68, expand: 60, outcome: 62 },
      { deals: 50, accuracy: 72, churn: 75, expand: 68, outcome: 70 },
      { deals: 60, accuracy: 78, churn: 80, expand: 74, outcome: 76 },
    ],
    locations: [
      { name: 'Arapahoe HQ', type: 'Office', lat: 39.5964, lng: -104.8690, status: 'on-net', lit: true, services: 1, mrr: 8500, products: ['IP Services'], note: 'Primary office + NOC. 1G DIA + DDoS.' },
      { name: 'Denver Data Center', type: 'Colo', lat: 39.7536, lng: -104.9998, status: 'on-net', lit: true, services: 1, mrr: 2100, products: ['zColo'], note: 'Edge colo for SCADA. One cab disconnected — migrated to AWS.' },
      { name: 'San Luis Valley Solar Site', type: 'Tower', lat: 37.4695, lng: -105.8700, status: 'off-net', lit: false, services: 0, mrr: 0, products: [], note: '400MW solar+storage. DOE funded. Fiber buildout opportunity.' },
      { name: 'Pueblo Solar Array', type: 'Tower', lat: 38.2970, lng: -104.5980, status: 'off-net', lit: false, services: 0, mrr: 0, products: [], note: 'Phase 2 solar installation. Needs SCADA connectivity.' },
      { name: 'Colorado Springs Substation', type: 'Remote Site', lat: 38.8339, lng: -104.8253, status: 'near-net', lit: false, services: 0, mrr: 0, products: [], note: 'Grid interconnection point. Fiber within 500ft.' },
      { name: 'AWS US-West-2 (Oregon)', type: 'Data Center', lat: 45.5946, lng: -122.1509, status: 'off-net', lit: false, services: 0, mrr: 0, products: [], note: 'Primary cloud region. Direct Connect prospect.' },
    ],
  },
]
